# Site settings
title: Rosie Holliday
twitter_username: hollidayrosie
name: Rosie Holliday

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks: 
 - title: GitHub
   url: https://github.com/rosiemcposie
 - title: LinkedIn
   url: https://www.linkedin.com/in/rosieholliday/

#Any buzzword skills you want to include
skills:
 - C#
 - .Net Core
 - Microservices
 - Server management
 - Product management
 - API design
 - React
 - Angular
 - MVC
 - Knockout
 - Java
 - JPA
 - SQL
 - Technical Architecture
 - Machine learning
 - VR
 - IOT

#Blogfeed is optional - including this will add JS to call the feed and populate blog list

#Work experience is required
roles:
 - title: Integration Specialist
   start: 2020
   end: Ongoing
   employer: Oak Engage
   description: Developing integrations between external products and a proprietary software. Managing documentation for the product as a whole.
 - title: Software Developer
   start: 2018
   end: 2020
   employer: Box Model Digital
   description: Creating, updating and maintaining websites and other systems for client businesses from inception, including speccing, project management, client liaison, development and testing.
 - title: Lead Developer
   start: 2017
   end: 2020
   employer: Unicorn Digital Solutions
   description: Creating web based solutions, apps and software for clients. Holding regular progress reviews with clients. Testing solutions. Learning new ways of working.
 - title: Graduate Developer
   start: 2015
   end: 2017
   employer: Northumberland County Council
   description: Creating and maintaining web based solutions. Using both front end and back end technologies. Liaising with members of staff of different levels. Mentoring new members of staff

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2016
   subject: Computer System Engineering
   school: University of Sunderland


intro: |
  I am a friendly, open person who likes meeting new people. My previous work experience has given me the opportunity to develop this into a transferable skill and I believe myself to be an extremely good communicator.  I have the ability to deal with external agencies as well as all levels of staff. I can form good working relationships with others and can work well within a team.  I am a motivated individual who can work individually and can use my initiative and can deal with problems as they arise.

Over the past 5 years I have developed, delivered and maintained effective customer centred solutions using C# .NET and SQL and front end technologies such as Javascript, Angular, AJAX and JSON, as well as front end frameworks such as React, Vue and Backbone. As I develop more systems I have been improving my business analysis and solution design skills.  This enables me to present my ideas and findings to peers and superiors as I become involved in more complex solutions.


#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
 <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using AWS.
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS. More recently I have written React mobile applications (primarily using the Expo framework, and extending them)<br/><br/>
   <strong>Development Process</strong>: I have a good knowledge of application life-cycle management and have worked with SVN and Git.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc), and Firebase. <br/><br/>
